---

- hosts: localhost
  tasks:
    - name: remove redundant packages
      apt:
          autoremove: yes
          force_apt_get: yes

    - name: display post install message
      debug:
        msg:
          - 'Manual steps left to do:'
          - '- git clone the dotfiles repo (optional)'
          - '- add noatime option for your SSD mounts points in /etc/fstab (optional)'
          - '- Install Papirus theme https://github.com/PapirusDevelopmentTeam/papirus-icon-theme'
          - '- install android studi via snap "sudo snap install android-studio --classic"'
          - '- enable WebRender in firefox; about:config in address bar, then manually set the gfx.webrender.enabled or gfx.webrender.all pref to true (optional)'
          - '- install / configure backup software for user data, apps, etc (optional)'
          - '- Reboot your system'

...
